### PR TITLE
Updated Yarn lockfile

### PR DESCRIPTION
**Pull request by fonta**

### CODE REVIEW

**Comment by cryptiklemur** [comment]
https://discord-service-definition.herokuapp.com/

**Comment by fonta** [comment]
Seems like some flags are needed for puppeteer. I'll do one more PR.
https://testdiscorddefgen.herokuapp.com/

**Comment by cryptiklemur** [comment]
https://hastebin.com/iqagonafef.makefile

**Comment by fonta** [comment]
[PR](https://github.com/aequasi/discord-service-definition-generator/pull/5) done for adding the sandbox flags. In my testapp on Heroku all seems to be OK now.

**Pull request merged**
